#!/bin/bash

TO="$1"
SUB="$2"
MES="$3"

function esc(){
	local escaped="'\''"
	echo "${1//\'/$escaped}"
}

function myesc {
	local escaped="\'"
	echo "${1//\'/$escaped}"
}

function sendemail {
	mailx -s "$SUB" "$TO"
}	

if [[ -f "$MES" ]]; then
	sendemail < "$MES"
else
        if [ $# -eq 4 ]; then
		sendemail < ~/email/tmp.txt
		rm ~/email/tmp.txt
	elif [ $# -eq 3 ]; then
		echo "`myesc \"$3\"`" | sendemail
	fi
fi
