#!/bin/bash

# Download Sublime Settings and Keymaps

curl https://raw.github.com/Gerst20051/dotfiles/master/Sublime2/User/Preferences.sublime-settings > ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/

echo "sublime sync complete"
