#!/bin/bash

# Download Git Settings

curl https://raw.github.com/Gerst20051/dotfiles/master/.gitconfig > ~/.gitconfig
curl https://raw.github.com/Gerst20051/dotfiles/master/.gitignore > ~/.gitignore

echo "git sync complete"
